In [1]:
%matplotlib notebook

import matplotlib.pyplot as plt
import numpy as np
import scipy.stats
import time

from vax_game import *
from bot import *

In [2]:
run(RandomBot, 100, show_stats=True)

Mean: 18.77
StdErr: 0.452516298049
Time:  0.19471311569213867


array([16, 15, 17, 21, 18, 17, 18, 19, 15, 17, 18, 23, 21, 17, 18, 23, 26,
       15, 21, 19, 17, 25, 20, 19, 17, 17, 19, 16, 16, 14, 16, 18, 14, 16,
       22, 17, 21, 16, 22, 18, 21, 15, 16, 18, 21, 23, 14, 18, 15, 20, 18,
       22, 16, 25, 19, 15, 15, 21, 43, 21, 22, 23, 16, 15, 22, 32, 18, 26,
       17, 13, 39, 15, 19, 14, 15, 18, 16, 17, 17, 22, 18, 17, 19, 18, 13,
       19, 13, 17, 21, 16, 19, 18, 19, 16, 16, 19, 20, 21, 18, 14])

In [3]:
run(DegreeBot, 100, show_stats=True)

Mean: 23.26
StdErr: 0.536026118767
Time:  0.20995593070983887


array([29, 34, 15, 23, 20, 20, 24, 26, 22, 32, 22, 21, 20, 33, 20, 34, 22,
       18, 24, 23, 27, 23, 18, 20, 20, 22, 24, 18, 15, 32, 19, 28, 25, 34,
       28, 37, 25, 20, 16, 20, 21, 21, 32, 23, 23, 17, 24, 15, 29, 21, 19,
       35, 31, 24, 15, 19, 26, 24, 19, 21, 13, 28, 25, 19, 22, 20, 22, 26,
       20, 18, 26, 21, 32, 25, 21, 25, 21, 22, 27, 20, 42, 29, 20, 21, 24,
       18, 24, 26, 25, 20, 20, 17, 26, 32, 17, 20, 18, 19, 20, 23])

In [4]:
run(NearbyBot, 100, show_stats=True)

Mean: 37.49
StdErr: 0.828310931957
Time:  0.22906804084777832


array([42, 41, 44, 28, 45, 41, 43, 46, 39, 39, 43, 40, 24, 45, 42, 46, 28,
       31, 17, 32, 34, 25, 32, 40, 47, 41, 18, 32, 47, 39, 35, 27, 27, 42,
       47, 47, 47, 33, 47, 23, 46, 38, 43, 26, 46, 35, 18, 47, 40, 47, 46,
       44, 43, 47, 37, 40, 27, 48, 40, 45, 47, 43, 40, 39, 38, 46, 43, 27,
       22, 42, 37, 29, 30, 45, 47, 27, 39, 31, 45, 29, 35, 29, 48, 32, 29,
       35, 39, 45, 41, 32, 45, 31, 38, 27, 46, 23, 46, 22, 27, 44])

In [3]:
run(DistanceBot.params(1, 2.2), 100, show_stats=True)

Mean: 42.67
StdErr: 0.520010576816
Time:  1.1781229972839355


array([42, 44, 44, 46, 48, 41, 39, 45, 41, 41, 47, 46, 43, 47, 18, 41, 36,
       44, 45, 45, 34, 39, 47, 45, 45, 45, 46, 48, 45, 43, 35, 45, 45, 44,
       43, 43, 47, 25, 44, 43, 42, 38, 48, 42, 44, 43, 34, 44, 45, 48, 44,
       33, 46, 45, 42, 46, 47, 46, 45, 36, 40, 48, 37, 41, 46, 46, 47, 39,
       47, 39, 39, 45, 47, 46, 29, 45, 42, 45, 46, 42, 45, 40, 36, 24, 46,
       46, 45, 46, 46, 48, 43, 47, 44, 46, 43, 44, 43, 37, 45, 45])

In [9]:
r1 = run(DistanceBot.params(1.1, 2.0), 2000)
r2 = run(DistanceBot.params(1.1, 1.8), 2000)
scipy.stats.ttest_ind(r2, r1)

Ttest_indResult(statistic=0.67277016185829253, pvalue=0.50113240547211002)